packages:
  - 'packages/*'

# Central dependency versions for catalog protocol
catalog:
  '@eslint/js': '^9.18.0'
  '@ls-stack/extended-lint': '^0.20.1'
  '@types/eslint': '^9.6.1'
  '@types/eslint__js': '^8.42.3'
  '@types/node': '^22.10.9'
  '@typescript-eslint/eslint-plugin': '^8.21.0'
  '@typescript-eslint/parser': '^8.21.0'
  '@vitest/ui': '^3.0.4'
  dequal: '^2.0.3'
  eslint: '^9.18.0'
  eslint-plugin-unicorn: '^56.0.1'
  eslint-plugin-vitest: '^0.5.4'
  evtmitter: '^0.3.3'
  mitata: '^1.0.32'
  prettier: '3.4.2'
  prettier-plugin-organize-imports: '^4.1.0'
  't-result': '^0.3.0'
  tsm: '^2.3.0'
  tsup: '^8.3.5'
  typedoc: '^0.28.4'
  typedoc-plugin-markdown: '^4.6.3'
  typedoc-plugin-missing-exports: '^4.0.0'
  typescript: '^5.7.3'
  'typescript-eslint': '^8.21.0'
  vite: '^6.0.11'
  vitest: '^3.0.4'
